version:     "0029a--12-Sep-2022"
copyright:   "2022"
author:      "Erlangga Ahmad Khadafi"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/erlanggaak/os222/"
myloglink:   "/TXT/mylog.txt"
mypublickey: "/TXT/mypubkey.txt"
mylinks:     "links.md"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
